<?php

/**
 * PluginComment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class PluginComment extends BaseComment
{
  public function setUp()
  {
    if(sfConfig::get('app_sfDoctrineActAsCommentable_user_enabled', false))
    {
      $userModel = sfConfig::get('app_sfDoctrineActAsCommentable_user_model', 'sfGuardUser');
      $userId = $userModel = sfConfig::get('app_sfDoctrineActAsCommentable_user_id', 'id');
      $columnName = Doctrine_Inflector::tableize($userModel) . "_$userId";
      $this->hasOne($userModel, array(
        'local' => 'author_id',
        'foreign' => $userId,
        'onDelete' => 'cascade'
      ));
    }
    parent::setUp();
  } 
  
  /**
   * Adds a reply to a comment
   * @param Comment $comment
   * @return 
   */
  public function addReply(Comment $comment)
  {
    $comment['commentable_model'] = $this['commentable_model'];
    $comment['commentable_id'] = $this['commentable_id'];
    
    return $comment->getNode()->insertAsLastChildOf($this);
  }
  
}